"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var styled_components_1 = require("styled-components");
var Overlay = styled_components_1.default.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  position: absolute;\n  width: 100%;\n  height: 99.5%;\n  bottom: 0px;\n  left: 0px;\n  z-index: 9999;\n  background: rgba(255, 255, 255, 0.1);\n  visibility: hidden;\n  opacity: 0;\n  transition: visibility 0s, opacity 0.25s linear;\n\n  &.show {\n    position: absolute;\n    left: 0px;\n    width: 100%;\n    height: 99.5%;\n    bottom: 0px;\n    visibility: visible;\n    opacity: 1;\n    transition: visibility 0s, opacity 0.1s linear;\n    z-index: 10000;\n  }\n"], ["\n  position: absolute;\n  width: 100%;\n  height: 99.5%;\n  bottom: 0px;\n  left: 0px;\n  z-index: 9999;\n  background: rgba(255, 255, 255, 0.1);\n  visibility: hidden;\n  opacity: 0;\n  transition: visibility 0s, opacity 0.25s linear;\n\n  &.show {\n    position: absolute;\n    left: 0px;\n    width: 100%;\n    height: 99.5%;\n    bottom: 0px;\n    visibility: visible;\n    opacity: 1;\n    transition: visibility 0s, opacity 0.1s linear;\n    z-index: 10000;\n  }\n"])));
var LoadingAnimation = styled_components_1.default.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  position: absolute;\n  top: 0px;\n  left: 0px;\n  width: 100%;\n  height: 0%;\n  background: rgba(255, 255, 255, 0.5);\n  z-index: 10000;\n  display: flex;\n  flex-direction: column;\n  align-items: center;\n  align-content: center;\n  justify-content: center;\n  visibility: hidden;\n  opacity: 0;\n  transition: height 0.25s, visibility 0s, opacity 0.25s linear;\n\n  background: linear-gradient(90deg, #3d9ee1, #a63de1, #3d9fe1);\n  background-size: 600% 600%;\n\n  -webkit-animation: AnimationName 2s ease infinite;\n  -moz-animation: AnimationName 2s ease infinite;\n  animation: AnimationName 2s ease infinite;\n\n  @-webkit-keyframes AnimationName {\n      0%{background-position:84% 0%}\n      50%{background-position:17% 100%}\n      100%{background-position:84% 0%}\n  }\n  @-moz-keyframes AnimationName {\n      0%{background-position:84% 0%}\n      50%{background-position:17% 100%}\n      100%{background-position:84% 0%}\n  }\n  @keyframes AnimationName {\n      0%{background-position:84% 0%}\n      50%{background-position:17% 100%}\n      100%{background-position:84% 0%}\n  }\n\n  &.show {\n    position: absolute;\n    top: 0px;\n    left: 0px;\n    width: 100%;\n    height: 0.5%;\n    visibility: visible;\n    opacity: 1;\n    transition: height 0.25s, visibility 0s, opacity 0.1s linear;\n    z-index: 10000;\n  }\n"], ["\n  position: absolute;\n  top: 0px;\n  left: 0px;\n  width: 100%;\n  height: 0%;\n  background: rgba(255, 255, 255, 0.5);\n  z-index: 10000;\n  display: flex;\n  flex-direction: column;\n  align-items: center;\n  align-content: center;\n  justify-content: center;\n  visibility: hidden;\n  opacity: 0;\n  transition: height 0.25s, visibility 0s, opacity 0.25s linear;\n\n  background: linear-gradient(90deg, #3d9ee1, #a63de1, #3d9fe1);\n  background-size: 600% 600%;\n\n  -webkit-animation: AnimationName 2s ease infinite;\n  -moz-animation: AnimationName 2s ease infinite;\n  animation: AnimationName 2s ease infinite;\n\n  @-webkit-keyframes AnimationName {\n      0%{background-position:84% 0%}\n      50%{background-position:17% 100%}\n      100%{background-position:84% 0%}\n  }\n  @-moz-keyframes AnimationName {\n      0%{background-position:84% 0%}\n      50%{background-position:17% 100%}\n      100%{background-position:84% 0%}\n  }\n  @keyframes AnimationName {\n      0%{background-position:84% 0%}\n      50%{background-position:17% 100%}\n      100%{background-position:84% 0%}\n  }\n\n  &.show {\n    position: absolute;\n    top: 0px;\n    left: 0px;\n    width: 100%;\n    height: 0.5%;\n    visibility: visible;\n    opacity: 1;\n    transition: height 0.25s, visibility 0s, opacity 0.1s linear;\n    z-index: 10000;\n  }\n"])));
exports.Loading = function (props) {
    return (React.createElement(React.Fragment, null,
        React.createElement(LoadingAnimation, { className: "loading " + (props.show ? "show" : "") }),
        React.createElement(Overlay, { className: "loading " + (props.show ? "show" : "") })));
};
var templateObject_1, templateObject_2;
//# sourceMappingURL=index.js.map