"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.COLORS = {
    "default": {
        BASE: {
            BACKGROUND_COLOR: "#007af5",
            COLOR: "white",
            BORDER_COLOR: "transparent",
        },
        ACTIVE: {
            BACKGROUND_COLOR: "#00ABF0",
            COLOR: "white",
            BORDER_COLOR: "transparent",
        },
        HOVER: {
            BACKGROUND_COLOR: "#045fba",
            COLOR: "white",
            BORDER_COLOR: "transparent",
        },
    },
    "red": {
        BASE: {
            BACKGROUND_COLOR: "#FC1449",
            COLOR: "white",
            BORDER_COLOR: "transparent",
        },
        ACTIVE: {
            BACKGROUND_COLOR: "#ad0c31",
            COLOR: "white",
            BORDER_COLOR: "transparent",
        },
        HOVER: {
            BACKGROUND_COLOR: "#d40d3a",
            COLOR: "white",
            BORDER_COLOR: "transparent",
        },
    },
    "blue": {
        BASE: {
            BACKGROUND_COLOR: "#00ABF0",
            COLOR: "white",
            BORDER_COLOR: "transparent",
        },
        ACTIVE: {
            BACKGROUND_COLOR: "#00ABF0",
            COLOR: "white",
            BORDER_COLOR: "transparent",
        },
        HOVER: {
            BACKGROUND_COLOR: "#007af5",
            COLOR: "white",
            BORDER_COLOR: "transparent",
        },
    },
    "blue-border": {
        BASE: {
            BACKGROUND_COLOR: "white",
            COLOR: "#007AF5",
            BORDER_COLOR: "#007AF5",
        },
        ACTIVE: {
            BACKGROUND_COLOR: "#007af5",
            COLOR: "rgba(255,255,255,0.8)",
            BORDER_COLOR: "#007AF5",
        },
        HOVER: {
            BACKGROUND_COLOR: "#007AF5",
            COLOR: "white",
            BORDER_COLOR: "#007AF5",
        },
    },
    "blue-outline": {
        BASE: {
            BACKGROUND_COLOR: "#ebf9ff",
            COLOR: "#00ABF0",
            BORDER_COLOR: "#00ABF0",
        },
        ACTIVE: {
            BACKGROUND_COLOR: "#007af5",
            COLOR: "white",
            BORDER_COLOR: "transparent",
        },
        HOVER: {
            BACKGROUND_COLOR: "#00ABF0",
            COLOR: "white",
            BORDER_COLOR: "transparent",
        },
    },
};
/*
  BACKGROUND: {
    "default": "#007af5",
    "light": "#F6F8F9",
    "red": "#FC1449",
    "rust": "#FF5300",
    "orange": "#FF9500",
    "yellow": "#F5C300",
    "lime": "#97D200",
    "green": "#0AD661",
    "teal": "#00C9AA",
    "blue": "#00ABF0",
    "royal": "#2685E7",
    "lavender": "#7F6AF8",
    "purple": "#B758EA",
    "pink": "#F551EA",
    "neon-pink": "#FE389F",
    "light-pink": "#FF89AD",
    "dark": "#88A4A7",
  },
  FOREGROUND: {
    "default": "#007af5",
    "light": "#F6F8F9",
    "red": "#FC1449",
    "rust": "#FF5300",
    "orange": "#FF9500",
    "yellow": "#F5C300",
    "lime": "#97D200",
    "green": "#0AD661",
    "teal": "#00C9AA",
    "blue": "#00ABF0",
    "royal": "#2685E7",
    "lavender": "#7F6AF8",
    "purple": "#B758EA",
    "pink": "#F551EA",
    "neon-pink": "#FE389F",
    "light-pink": "#FF89AD",
    "dark": "#88A4A7",
  },
  FOREGROUND: {
    "default": "#007af5",
    "light": "#F6F8F9",
    "red": "#FC1449",
    "rust": "#FF5300",
    "orange": "#FF9500",
    "yellow": "#F5C300",
    "lime": "#97D200",
    "green": "#0AD661",
    "teal": "#00C9AA",
    "blue": "#00ABF0",
    "royal": "#2685E7",
    "lavender": "#7F6AF8",
    "purple": "#B758EA",
    "pink": "#F551EA",
    "neon-pink": "#FE389F",
    "light-pink": "#FF89AD",
    "dark": "#88A4A7",
  },
  BORDER: {
    "default": "#007af5",
    "light": "#F6F8F9",
    "red": "#FC1449",
    "rust": "#FF5300",
    "orange": "#FF9500",
    "yellow": "#F5C300",
    "lime": "#97D200",
    "green": "#0AD661",
    "teal": "#00C9AA",
    "blue": "#00ABF0",
    "royal": "#2685E7",
    "lavender": "#7F6AF8",
    "purple": "#B758EA",
    "pink": "#F551EA",
    "neon-pink": "#FE389F",
    "light-pink": "#FF89AD",
    "dark": "#88A4A7",
  },
*/
//# sourceMappingURL=colors.js.map